"""Tektronix AWG5208 driver and functional waveform helpers."""

from .driver import (
    AWG5208,
    TriggerConfig,
    TriggerInput,
    TriggerSlope,
)
from .transport import ScpiTransport, open_visa_transport
from ..timeline import (
    Delay,
    Parallel,
    Timeline,
    Waveform,
    align_channel_envelopes,
    align_channels,
    channel_names,
    delay,
    delay_auto,
    parallel,
    waveform,
)
from .waveforms import (
    concatenate,
    constant,
    cosine_square,
    cosine_square_ns,
    gaussian,
    gaussian_cosine,
    gaussian_cosine_ns,
    gaussian_square,
    gaussian_square_ns,
    make_wfmx,
    marker_window,
    marker_window_ns,
    modulate_envelope,
    ns_to_samples,
    sample_count,
    sine,
    time_axis,
    time_axis_ns,
    trigger_channel_for,
    triangle_ns,
)

__all__ = [
    "AWG5208",
    "Delay",
    "Parallel",
    "ScpiTransport",
    "Timeline",
    "TriggerConfig",
    "TriggerInput",
    "TriggerSlope",
    "Waveform",
    "align_channel_envelopes",
    "align_channels",
    "channel_names",
    "concatenate",
    "constant",
    "cosine_square",
    "cosine_square_ns",
    "delay",
    "delay_auto",
    "gaussian",
    "gaussian_cosine",
    "gaussian_cosine_ns",
    "gaussian_square",
    "gaussian_square_ns",
    "triangle_ns",
    "marker_window",
    "marker_window_ns",
    "modulate_envelope",
    "ns_to_samples",
    "open_visa_transport",
    "parallel",
    "sample_count",
    "sine",
    "time_axis",
    "time_axis_ns",
    "trigger_channel_for",
    "waveform",
]
