"""Small, QCoDeS-free ATS9371 acquisition package."""

from .ats9371 import (
    AcquisitionConfig,
    BoardInfo,
    CaptureSession,
    DmaBuffer,
    TriggerConfig,
    abort_capture,
    adc_codes_to_volts,
    analyze_tone,
    arm_capture,
    configure_ats9371,
    configure_channel,
    free_capture,
    get_board_info,
    open_ats9371,
    start_capture,
    wait_for_capture,
)
from .ats_api import ATSApi, AlazarError
from .processor import AlazarProcessor
from .demodulation import (
    acquire,
    correct_interleaving_offsets,
    digital_downconvert,
    acquire_decimate,
    moving_average_time_axis,
    phase_align_iq,
    recover_coherent_envelope,
    recover_clock_referenced_envelope,
    subtract_baseline,
)

__all__ = [
    "ATSApi",
    "AcquisitionConfig",
    "AlazarError",
    "AlazarProcessor",
    "BoardInfo",
    "CaptureSession",
    "DmaBuffer",
    "TriggerConfig",
    "abort_capture",
    "adc_codes_to_volts",
    "analyze_tone",
    "acquire",
    "correct_interleaving_offsets",
    "arm_capture",
    "configure_ats9371",
    "configure_channel",
    "digital_downconvert",
    "acquire_decimate",
    "free_capture",
    "get_board_info",
    "moving_average_time_axis",
    "phase_align_iq",
    "recover_coherent_envelope",
    "recover_clock_referenced_envelope",
    "open_ats9371",
    "start_capture",
    "subtract_baseline",
    "wait_for_capture",
]
